name: smart_encrypt
description: library for easy use encrypt & decrypt features, generate bytes & string
version: 1.0.3
homepage: https://github.com/Anykeykin/smart_encrypt

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.3
  encrypt: ^5.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
